### PR TITLE
Feature/structure

### PR DESCRIPTION
**Pull request by Albinpirela**
# Added structure and functionality
image

### CODE REVIEW

**Review by GerardoGomezG — CHANGES_REQUESTED** [review]
Hello my dear friend @Albinpirela !

It's been a whole challenge to accomplish the scope of this project, so cheers 🍻 for what you've done so far... You've even done part of the next stage of the project: which is _Adding a new task when typing and hitting the Enter key from text input field_, so that's great!

Before approving your PR, I suggest doing the following changes:

- The design considers 3 predefined tasks to load when there's no task saved in the Local Storage, so I suggest to load those tasks:
image

- Improve To Do List display for small and medium screen sizes devices. As you can see in the following pic, a vertical scroll bar is generated despite the To Do List size would fit in the screen size
image

- This project is with no Figma nor Adobe XD design, so as the great frontend developer that you are, you're able to figure out the styles (box-shadow, blank spaces, fonts, shapes, etc.) of this project in this first stage, so you won't have to worry about styling when on the second stage

Your project design so far:
image

What you're able to accomplish:
image

💪🏻 Keep on coding bro!

**Comment by Albinpirela** [comment]
> Hello my dear friend @Albinpirela !
> 
> It's been a whole challenge to accomplish the scope of this project, so cheers 🍻 for what you've done so far... You've even done part of the next stage of the project: which is _Adding a new task when typing and hitting the Enter key from text input field_, so that's great!
> 
> Before approving your PR, I suggest doing the following changes:
> 
> * The design considers 3 predefined tasks to load when there's no task saved in the Local Storage, so I suggest to load those tasks:
>   image
> * Improve To Do List display for small and medium screen sizes devices. As you can see in the following pic, a vertical scroll bar is generated despite the To Do List size would fit in the screen size
>   image
> * This project is with no Figma nor Adobe XD design, so as the great frontend developer that you are, you're able to figure out the styles (box-shadow, blank spaces, fonts, shapes, etc.) of this project in this first stage, so you won't have to worry about styling when on the second stage
> 
> Your project design so far: image
> 
> What you're able to accomplish: image
> 
> 💪🏻 Keep on coding bro!



> Hello my dear friend @Albinpirela !
> 
> It's been a whole challenge to accomplish the scope of this project, so cheers 🍻 for what you've done so far... You've even done part of the next stage of the project: which is _Adding a new task when typing and hitting the Enter key from text input field_, so that's great!
> 
> Before approving your PR, I suggest doing the following changes:
> 
> * The design considers 3 predefined tasks to load when there's no task saved in the Local Storage, so I suggest to load those tasks:
>   image
> * Improve To Do List display for small and medium screen sizes devices. As you can see in the following pic, a vertical scroll bar is generated despite the To Do List size would fit in the screen size
>   image
> * This project is with no Figma nor Adobe XD design, so as the great frontend developer that you are, you're able to figure out the styles (box-shadow, blank spaces, fonts, shapes, etc.) of this project in this first stage, so you won't have to worry about styling when on the second stage
> 
> Your project design so far: image
> 
> What you're able to accomplish: image
> 
> 💪🏻 Keep on coding bro!

# Thank you very much for your attention dear friend, I have seen and corrected and made the required changes I hope you like them
🦺

**Review by GerardoGomezG — COMMENTED** [review]
Great @Albinpirela !

The list is adding the 3 predefined tasks now.

Are you planning to work on the new task input style and on the tasks lines separators in the next stage?

**Comment by Albinpirela** [comment]
> Great @Albinpirela !
> 
> The list is adding the 3 predefined tasks now.
> 
> Are you planning to work on the new task input style and on the tasks lines separators in the next stage?

# Excellent observation my friend, I had problems with the resolution of the screen. That's why I didn't see them, but the problem is already solved.

**Review by GerardoGomezG — APPROVED** [review]

**Review by GerardoGomezG — APPROVED** [review]
Well done bro!

Congratulations @Albinpirela ! 💪🏻

**Pull request merged**
